src/test/resources/journeys.conf
src/test/resources/logback.xml
src/test/scala/uk/gov/hmrc/perftests/istass/IncomeTaxSubmissionSimulation.scala

Updated Logging Levels to WARN for better running clarity, relabelled journeys to simplify addition of future flows.

SASS-49b : Updated Logging and specified Journeys for future expansion

---

src/test/scala/uk/gov/hmrc/perftests/itsass/AuthLoginRequests.scala

Updated url to match the correct suffix in the auth login step
SASS-perffix

SASS-perffix : rectified agent login url

---

src/test/scala/uk/gov/hmrc/perftests/itsass/DividendsRequests.scala

SASS-652 updated urls

---

project/Dependencies.scala
project/build.properties
project/plugins.sbt
src/test/resources/gatling.conf
src/test/resources/logback.xml
src/test/scala/uk/gov/hmrc/perftests/itsass/AuthLoginRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/DividendsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/InterestRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/RequestsHelper.scala

Performance test runner upgrade along with gatling and other dependancies.
[SASS-494](https://jira.tools.tax.service.gov.uk/browse/SASS-494)

SASS-494 : Performance Runner upgrade along with other dependancies

---

project/Dependencies.scala
project/plugins.sbt

Updating dependencies
https://jira.tools.tax.service.gov.uk/browse/SASS-830

SASS-830: Updating dependencies

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/EmploymentsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/RequestsHelper.scala

Add performance tests for adding an employment journey
https://jira.tools.tax.service.gov.uk/browse/SASS-1144

performance tests for adding an employment

---

src/test/scala/uk/gov/hmrc/perftests/itsass/AuthLoginRequests.scala

Based on Auth Login Changes
SASS-NA

Removed CSRF Token Check on auth page

---

src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

Added performance tests for new accommodation relocation section
https://jira.tools.tax.service.gov.uk/browse/SASS-1391
To be merged alongside hmrc/income-tax-submission-journey-tests#99 & https://github.com/hmrc/income-tax-employment-frontend/pull/160

added accommodation relocation tests

---

src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

- Added utilities benefits flows
https://jira.tools.tax.service.gov.uk/browse/SASS-1534

SASS-1534: Added utilities benefits flows

---

src/test/scala/uk/gov/hmrc/perftests/itsass/RequestsHelper.scala

Change all `/income-through-software/return/` strings to `/update-and-submit-income-tax-return/`
[SASS-1573](https://jira.tools.tax.service.gov.uk/browse/SASS-1573)

SASS-1573: Update performance tests page URLs

---

src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

https://jira.tools.tax.service.gov.uk/browse/SASS-1690

added medical tests

---

src/test/scala/uk/gov/hmrc/perftests/itsass/EmploymentsRequests.scala

Expenses - Change to Expenses CYA page URL 
https://jira.tools.tax.service.gov.uk/browse/SASS-1645
NOTE
THESE CHANGES ARE FOR [THIS PR](https://github.com/hmrc/income-tax-employment-frontend/pull/210)

SASS-1645 - Expenses - Change to CYA page URL

---

project/plugins.sbt
src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

added tests for income tax or incurred costs section.
Merge with SASS-1745
[SASS-1658](https://jira.tools.tax.service.gov.uk/browse/SASS-1658)

SASS-1747 - added performance tests for income tax or incurred costs section of employment benefits

---

README.md
run_nrs_smoke_tests.sh
run_smoke_tests.sh
src/test/resources/journeys.conf
src/test/resources/services-local.conf
src/test/resources/services.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/AuthLoginAPIRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/Json/NRSRequest.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/NRSProxyRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/utils/NumberGenerator.scala

Added NRS Performance functionality, and separated existing journeys
THIS NEEDS TO BE MERGED FIRST (https://github.com/hmrc/performance-test-jobs/pull/405)
[SASS-1467](https://jira.tools.tax.service.gov.uk/browse/SASS-1467)

SASS-1467 : Added NRS Specific Journey Test

---

src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

added tests for reimbursed costs, vouchers and non cash section of employment benefits
[SASS-1725](https://jira.tools.tax.service.gov.uk/browse/SASS-1725)

SASS-1725 - added tests for reimbursed costs benefits section

---

src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

updated tests with assets section of employment benefits
[SASS-1726](https://jira.tools.tax.service.gov.uk/browse/SASS-1726)

SASS-1726 - added tests for assets section of employment benefits

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/ExpensesRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

Subtask [SASS-1867](https://jira.tools.tax.service.gov.uk/browse/SASS-1867) for [SASS-1662](https://jira.tools.tax.service.gov.uk/browse/SASS-1662) Employment Expenses end of year navigation

SASS-1867 add tests for Expenses journey

---

src/test/scala/uk/gov/hmrc/perftests/itsass/EmploymentsRequests.scala

Changed url of a request.
[SASS-1124](https://jira.tools.tax.service.gov.uk/browse/SASS-1124)

SASS-1124 Changed a url

---

project/Dependencies.scala
src/test/resources/application.conf
src/test/resources/gatling.conf
src/test/resources/journeys.conf
src/test/resources/services-local.conf
src/test/resources/services.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/AuthLoginAPIRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/AuthLoginRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/BenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/CrystallisationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/DividendsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/EmploymentsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/ExpensesRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/GiftAidRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/InterestRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/Json/NRSRequest.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/NRSProxyRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/utils/NumberGenerator.scala

Added navigation for entire flow when adding a new employment
[SASS-1664 Navigation for entire flow when adding a new employment](https://jira.tools.tax.service.gov.uk/browse/SASS-1664)

Sass 1664 Navigation for entire flow when adding a new employment

---

src/test/scala/uk/gov/hmrc/perftests/itsass/EmploymentsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala

- Employment Summary Iteration
https://jira.tools.tax.service.gov.uk/browse/SASS-2042

SASS-2042: Employment Summary Iteration

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/CrystallisationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/IncomeTaxSubmissionRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/ViewEstimationSimSteps.scala

SASS-2344 View estimation performance tests
[SASS-2344](https://jira.tools.tax.service.gov.uk/browse/SASS-2211)

SASS-2344 view estimation perf tests

---

src/test/resources/journeys.conf
src/test/resources/services-local.conf
src/test/resources/services.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/EmploymentsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/EmploymentsSimSteps.scala

Some small refactor changes and fixes

SASS-empRefactorLite : Some small refactor changes

---

src/test/resources/journeys.conf
src/test/resources/services-local.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/PaymentsIntoPensionsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PensionsSimSteps.scala

Performance test for payments into pensions
[SASS-2097](https://jira.tools.tax.service.gov.uk/browse/SASS-2097)

SASS-2097 Payments into Pensions

---

src/test/resources/journeys.conf
src/test/resources/services-local.conf
src/test/resources/services.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PensionsSimSteps.scala

Added pensions frontend to services.conf

SASS-2097 : Added pensions frontend to services.conf

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/CISRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/CISSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/utils/TaxYearHelper.scala

[SASS-2922](https://jira.tools.tax.service.gov.uk/browse/SASS-2922)

SASS-2176 - Update performance tests

---

README.md
src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/CrystallisationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala

Updated V&C requests with origin Query parameter
[SASS-2772](https://jira.tools.tax.service.gov.uk/browse/SASS-2772)

SASS-2772 : Added origin Query parameter to View and Change requests

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/CrystallisationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/IncomeTaxSubmissionRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/CrystallisationSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/ViewEstimationSimSteps.scala

[SASS-2772](https://jira.tools.tax.service.gov.uk/browse/SASS-2772)

SASS-2772 : Further Perf test changes to address Origin parameter query

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/InterestRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/InterestSimSteps.scala

Added gateway steps to interest journey
[SASS-2833](https://jira.tools.tax.service.gov.uk/browse/SASS-2833)

SASS-2833 : Added gateway steps to interest journey

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/CrystallisationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/DividendsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/CrystallisationSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/DividendsSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/ViewEstimationSimSteps.scala

Added dividends gateway step to dividends journeys
[SASS-2834](https://jira.tools.tax.service.gov.uk/browse/SASS-2834)

SASS-2834 : Added dividends gateway step to dividends journeys

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala

Change status code assertion for overview page test.
[SASS-3237](https://jira.tools.tax.service.gov.uk/browse/SASS-3237)

SASS-3237: Change status code assertion for overview page test

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala

Reverts hmrc/income-tax-submission-performance-tests#77

Revert "SASS-3237: Change status code assertion for overview page test"

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/CrystallisationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/ViewEstimationRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/CrystallisationSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/ViewEstimationSimSteps.scala

SASS-3237 - Changed ninos specified and update status code assertions.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/EmploymentsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/EmploymentsSimSteps.scala

[SASS-3507](https://jira.tools.tax.service.gov.uk/browse/SASS-3507)

SASS-3507 - Performance tests for Employment Benefits pages failing.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

[SASS-3591](https://jira.tools.tax.service.gov.uk/browse/SASS-3591)

SASS-3591 - Create 'When did you start getting JSA?' page.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

[SASS-3591](https://jira.tools.tax.service.gov.uk/browse/SASS-3591)

SASS-3591 - Create 'When did you start getting JSA?' page

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

[SASS-3595](https://jira.tools.tax.service.gov.uk/browse/SASS-3595)

SASS-3595 - Create 'When did this claim end?' page.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

[SASS-3592](https://jira.tools.tax.service.gov.uk/browse/SASS-3592)

SASS-3592 - Create 'Did this claim end in the tax year?' page.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StudentLoansRequests.scala

Student loans performance tests update

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

[SASS-3678](https://jira.tools.tax.service.gov.uk/browse/SASS-3678)

SASS-3678 - Create 'Did you have tax taken off?' page.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

Create 'Review Jobseeker's Allowance claim' Page for Customer Data & HMRC data
[SASS-3681](https://jira.tools.tax.service.gov.uk/browse/SASS-3681)

SASS-3681 Create 'Review Jobseeker's Allowance claim' Page for Customer Data & HMRC data

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

Create 'Are you sure you want to remove JSA claim?' page
[SASS-3694](https://jira.tools.tax.service.gov.uk/browse/SASS-3694)

SASS-3694 Create 'Are you sure you want to remove JSA claim?' page

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

[SASS-3715](https://jira.tools.tax.service.gov.uk/browse/SASS-3715)

SASS-3715 - JSA 'Restore claim' functionality & navigation.

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/StateBenefitsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/StateBenefitsSimSteps.scala

Create 'have you completed this section?' page.
[SASS-3955](https://jira.tools.tax.service.gov.uk/browse/SASS-3955)

SASS-3955 - Create 'have you completed this section?' page.

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/UnauthorisedPaymentsFromPensionsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PensionsSimSteps.scala

Performance test for unauthorised payment from pension
[SASS-4128](https://jira.tools.tax.service.gov.uk/browse/SASS-4128)

SASS-4128 Navigation for unauthorised payment from pension

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/InterestRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/InterestSimSteps.scala

Sass 3621 temp

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/DividendsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala

add stock dividends to test

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala

SASS-tailor-return-fix

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AboutYourWorkRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AboutYourWorkSimSteps.scala

About your work

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/IncomeFromPropertyPensionsInvestmentsRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/IncomeFromPropertyPensionsInvestmentsSimSteps.scala

test for property pensions and investments

---

src/test/resources/journeys.conf
src/test/resources/services-local.conf
src/test/resources/services.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/TailorReturnRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/TailorReturnSimSteps.scala

tailor return performance test

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala

amend tailor return url

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/DividendsSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/InterestSimSteps.scala

update perf test

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/TailorReturnRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/TailorReturnSimSteps.scala

SASS-6388 Income from work performance test

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/TailorReturnRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/TailorReturnSimSteps.scala

SASS 6404 add tests for payments into pensions

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/PropertyUKRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PropertyUKSimSteps.scala

NonJIRAUK Property performance Test

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala

edit value for interest test

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala

amend performance load numbers

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala

added new endpoints for section completed pages

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala

fix performance test

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/GiftAidRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/GiftAidSimSteps.scala

SASS-10294

---

src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PropertyUKSimSteps.scala

Added the UK and foreign property PTs

---

src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/PropertyForeignRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/PropertyUKAndForeignRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PropertyForeignSimSteps.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PropertyUKAndForeignSimSteps.scala

Added foreign and UK & Foreign property journeys

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/PropertyUKAndForeignRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/PropertyUKAndForeignSimSteps.scala

1. Claim expenses or rent a room relief
2. Claim property income allowance or expenses
3. Non-UK resident

Added performance tests 

---

README.md
src/test/resources/journeys.conf
src/test/scala/uk/gov/hmrc/perftests/itsass/IncomeTaxSubmissionSimulation.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/AdditionalInfoRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/RequestsHelper.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/AdditionalInformationSimSteps.scala

SASS-11474: Post-cessation performance tests

---

src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/SelfEmploymentExpensesSimStepsFS.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/SelfEmploymentTradingAllowanceFSSimSteps.scala

Added feature switch simStep files for SE

---

src/test/scala/uk/gov/hmrc/perftests/itsass/requests/SelfEmploymentExpensesRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/requests/SelfEmploymentTradingAllowanceRequests.scala
src/test/scala/uk/gov/hmrc/perftests/itsass/simSteps/SelfEmploymentExpensesSimSteps.scala

Added travel and accom MVP to PTs
